const questions = [
    // --- Banking Basics ---
    { id: 1, category: "Banking Basics", difficulty: "Easy", question: "What is the full form of ATM?", options: ["Automated Teller Machine", "Any Time Money", "Auto Transaction Machine", "Active Teller Management"], answer: "Automated Teller Machine" },
    { id: 2, category: "Banking Basics", difficulty: "Easy", question: "Which bank is known as the 'Banker's Bank' in India?", options: ["SBI", "RBI", "PNB", "ICICI"], answer: "RBI" },
    { id: 3, category: "Banking Basics", difficulty: "Medium", question: "What is the minimum age required to open a bank account in India independently?", options: ["10 years", "18 years", "15 years", "21 years"], answer: "10 years" },
    { id: 4, category: "Banking Basics", difficulty: "Medium", question: "Which of the following is NOT a type of bank deposit?", options: ["Savings Account", "Current Account", "Fixed Deposit", "Demand Loan"], answer: "Demand Loan" },
    { id: 5, category: "Banking Basics", difficulty: "Hard", question: "What is the full form of CAMELS in banking supervision?", options: ["Capital, Assets, Management, Earnings, Liquidity, Sensitivity", "Cash, Assets, Money, Equity, Loans, Securities", "Capital, Account, Management, Equity, Loss, Solvency", "Credit, Assets, Management, Earnings, Liability, Stability"], answer: "Capital, Assets, Management, Earnings, Liquidity, Sensitivity" },
    { id: 6, category: "Banking Basics", difficulty: "Easy", question: "What is a 'Cheque'?", options: ["A bill of exchange", "A credit card", "A cash receipt", "A loan agreement"], answer: "A bill of exchange" },
    { id: 7, category: "Banking Basics", difficulty: "Medium", question: "The term 'Plastic Money' refers to?", options: ["Credit Cards", "Currency Notes", "Coins", "Vouchers"], answer: "Credit Cards" },
    { id: 8, category: "Banking Basics", difficulty: "Hard", question: "What is 'Escrow Account'?", options: ["A temporary account held by a third party", "A savings account for senior citizens", "An account for NRI", "A fixed deposit account"], answer: "A temporary account held by a third party" },
    { id: 9, category: "Banking Basics", difficulty: "Easy", question: "What does PAN stand for?", options: ["Permanent Account Number", "Personal Account Name", "Public Access Network", "Primary Account Note"], answer: "Permanent Account Number" },
    { id: 10, category: "Banking Basics", difficulty: "Medium", question: "Which rate is used by RBI to lend money to commercial banks for short term?", options: ["Repo Rate", "Reverse Repo Rate", "Bank Rate", "CRR"], answer: "Repo Rate" },

    // --- Financial Accounting ---
    { id: 11, category: "Financial Accounting", difficulty: "Easy", question: "What is the basic accounting equation?", options: ["Assets = Liabilities + Equity", "Assets = Liabilities - Equity", "Liabilities = Assets + Equity", "Equity = Assets + Liabilities"], answer: "Assets = Liabilities + Equity" },
    { id: 12, category: "Financial Accounting", difficulty: "Medium", question: "Which accounting principle states that 'Every transaction has two aspects'?", options: ["Dual Aspect Principle", "Going Concern Principle", "Consistency Principle", "Materiality Principle"], answer: "Dual Aspect Principle" },
    { id: 13, category: "Financial Accounting", difficulty: "Hard", question: "What is 'Amortization'?", options: ["Writing off intangible assets", "Depreciation of land", "Increasing the value of assets", "Interest on loans"], answer: "Writing off intangible assets" },
    { id: 14, category: "Financial Accounting", difficulty: "Easy", question: "Goodwill is which type of asset?", options: ["Intangible Asset", "Tangible Asset", "Current Asset", "Fictitious Asset"], answer: "Intangible Asset" },
    { id: 15, category: "Financial Accounting", difficulty: "Medium", question: "What is 'Tally' in the context of business?", options: ["Accounting Software", "Inventory System", "Marketing Tool", "HR Management"], answer: "Accounting Software" },
    { id: 16, category: "Financial Accounting", difficulty: "Hard", question: "A 'Trial Balance' is prepared to check?", options: ["Arithmetical Accuracy", "Net Profit", "Financial Position", "Cash Balance"], answer: "Arithmetical Accuracy" },
    { id: 17, category: "Financial Accounting", difficulty: "Easy", question: "Which account is credited when goods are sold for cash?", options: ["Sales Account", "Cash Account", "Purchases Account", "Customer Account"], answer: "Sales Account" },
    { id: 18, category: "Financial Accounting", difficulty: "Medium", question: "What is 'Accrual Accounting'?", options: ["Recording transactions when they occur", "Recording transactions when cash is received", "Recording only credit transactions", "Recording only tax liabilities"], answer: "Recording transactions when they occur" },
    { id: 19, category: "Financial Accounting", difficulty: "Hard", question: "What is the treatment of 'Outstanding Salary' in Final Accounts?", options: ["Liability in Balance Sheet", "Asset in Balance Sheet", "Income in P&L", "Reduction from Cash"], answer: "Liability in Balance Sheet" },
    { id: 20, category: "Financial Accounting", difficulty: "Easy", question: "Ledger is a book of?", options: ["Final Entry", "Original Entry", "Primary Entry", "Cash Entry"], answer: "Final Entry" },

    // --- Business Economics ---
    { id: 21, category: "Business Economics", difficulty: "Easy", question: "Who is known as the Father of Economics?", options: ["Adam Smith", "Alfred Marshall", "J.M. Keynes", "Karl Marx"], answer: "Adam Smith" },
    { id: 22, category: "Business Economics", difficulty: "Medium", question: "What does 'Elasticity of Demand' measure?", options: ["Responsiveness of quantity demanded to price change", "Change in supply", "Change in income", "Market competition"], answer: "Responsiveness of quantity demanded to price change" },
    { id: 23, category: "Business Economics", difficulty: "Hard", question: "What is 'Giffen Good'?", options: ["A low-income product that defies standard demand laws", "A luxury product", "A complementary good", "A substitute good"], answer: "A low-income product that defies standard demand laws" },
    { id: 24, category: "Business Economics", difficulty: "Easy", question: "What is 'Monopoly'?", options: ["Single seller market", "Two sellers market", "Many sellers market", "No seller market"], answer: "Single seller market" },
    { id: 25, category: "Business Economics", difficulty: "Medium", question: "What is 'Opportunity Cost'?", options: ["The cost of the next best alternative foregone", "The actual money spent", "The fixed cost of production", "The variable cost"], answer: "The cost of the next best alternative foregone" },
    { id: 26, category: "Business Economics", difficulty: "Hard", question: "The 'Law of Diminishing Marginal Utility' states?", options: ["Utility decreases as consumption increases", "Utility increases as consumption increases", "Utility remains constant", "Utility is always zero"], answer: "Utility decreases as consumption increases" },
    { id: 27, category: "Business Economics", difficulty: "Easy", question: "What is GDP?", options: ["Gross Domestic Product", "General Domestic Price", "Gross Deposit Portfolio", "Global Development Plan"], answer: "Gross Domestic Product" },
    { id: 28, category: "Business Economics", difficulty: "Medium", question: "In a 'Perfect Competition', products are?", options: ["Homogeneous", "Differentiated", "Unique", "Branded"], answer: "Homogeneous" },
    { id: 29, category: "Business Economics", difficulty: "Hard", question: "What is 'Stagflation'?", options: ["High inflation + High unemployment", "Low inflation + Low unemployment", "High inflation + Low unemployment", "Low inflation + High unemployment"], answer: "High inflation + High unemployment" },
    { id: 30, category: "Business Economics", difficulty: "Easy", question: "What is the main motive of a firm in economics?", options: ["Profit Maximization", "Social Welfare", "Tax Evasion", "Charity"], answer: "Profit Maximization" },

    // --- Financial Management ---
    { id: 31, category: "Financial Management", difficulty: "Easy", question: "What is the goal of Financial Management?", options: ["Wealth Maximization", "Cost Minimization", "Sales Maximization", "Tax Maximization"], answer: "Wealth Maximization" },
    { id: 32, category: "Financial Management", difficulty: "Medium", question: "What is 'WACC'?", options: ["Weighted Average Cost of Capital", "Weekly Account Credit Card", "World Asset Control Center", "Working Asset Cost Calculation"], answer: "Weighted Average Cost of Capital" },
    { id: 33, category: "Financial Management", difficulty: "Hard", question: "The 'Payback Period' method ignores?", options: ["Time Value of Money", "Initial Investment", "Total Profit", "Cash Outflows"], answer: "Time Value of Money" },
    { id: 34, category: "Financial Management", difficulty: "Easy", question: "What is 'Current Ratio'?", options: ["Current Assets / Current Liabilities", "Total Assets / Total Liabilities", "Cash / Debt", "Revenue / Expenses"], answer: "Current Assets / Current Liabilities" },
    { id: 35, category: "Financial Management", difficulty: "Medium", question: "What is 'Capital Budgeting'?", options: ["Long-term investment decision", "Short-term cash management", "Daily expense tracking", "Salary distribution"], answer: "Long-term investment decision" },
    { id: 36, category: "Financial Management", difficulty: "Hard", question: "What is 'Financial Leverage'?", options: ["Use of debt in capital structure", "Use of equity in capital structure", "Use of cash in daily operations", "Use of assets for collateral"], answer: "Use of debt in capital structure" },
    { id: 37, category: "Financial Management", difficulty: "Easy", question: "Which of these is a source of long-term finance?", options: ["Equity Shares", "Trade Credit", "Bank Overdraft", "Commercial Paper"], answer: "Equity Shares" },
    { id: 38, category: "Financial Management", difficulty: "Medium", question: "What is 'Working Capital'?", options: ["Current Assets - Current Liabilities", "Fixed Assets + Cash", "Total Revenue - Total Cost", "Equity + Debt"], answer: "Current Assets - Current Liabilities" },
    { id: 39, category: "Financial Management", difficulty: "Hard", question: "Gordon's Model is related to?", options: ["Dividend Policy", "Capital Structure", "Working Capital", "Inventory Management"], answer: "Dividend Policy" },
    { id: 40, category: "Financial Management", difficulty: "Easy", question: "What is 'EBIT'?", options: ["Earnings Before Interest and Taxes", "Earnings Between Income and Tax", "Equity Balance in Trust", "Estimated Budget in Transit"], answer: "Earnings Before Interest and Taxes" },

    // --- Stock Market Basics ---
    { id: 41, category: "Stock Market Basics", difficulty: "Easy", question: "What is 'BSE'?", options: ["Bombay Stock Exchange", "Bharat Stock Equity", "Basic Stock Energy", "Board of Stock Exchange"], answer: "Bombay Stock Exchange" },
    { id: 42, category: "Stock Market Basics", difficulty: "Medium", question: "What is a 'Blue Chip' company?", options: ["A large, well-established, financially sound company", "A new startup", "A company in loss", "A software company"], answer: "A large, well-established, financially sound company" },
    { id: 43, category: "Stock Market Basics", difficulty: "Hard", question: "What is 'Nifty 50'?", options: ["Index of top 50 companies on NSE", "Index of top 50 companies on BSE", "A new crypto coin", "A 50% discount scheme"], answer: "Index of top 50 companies on NSE" },
    { id: 44, category: "Stock Market Basics", difficulty: "Easy", question: "What is an 'IPO'?", options: ["Initial Public Offering", "Internal Profit Option", "International Price Order", "Investment Portfolio Object"], answer: "Initial Public Offering" },
    { id: 45, category: "Stock Market Basics", difficulty: "Medium", question: "What is 'Dividend'?", options: ["A portion of profit paid to shareholders", "A type of loan", "A tax on shares", "A trading fee"], answer: "A portion of profit paid to shareholders" },
    { id: 46, category: "Stock Market Basics", difficulty: "Hard", question: "What is 'Bull Market'?", options: ["When stock prices are rising", "When stock prices are falling", "When market is closed", "When trading is suspended"], answer: "When stock prices are rising" },
    { id: 47, category: "Stock Market Basics", difficulty: "Easy", question: "Which regulator controls the stock market in India?", options: ["SEBI", "RBI", "IRDAI", "PFRDA"], answer: "SEBI" },
    { id: 48, category: "Stock Market Basics", difficulty: "Medium", question: "What is a 'Demat Account'?", options: ["Account to hold shares in electronic form", "A fixed deposit account", "A zero balance account", "A corporate account"], answer: "Account to hold shares in electronic form" },
    { id: 49, category: "Stock Market Basics", difficulty: "Hard", question: "What is 'Short Selling'?", options: ["Selling shares you don't own to buy back cheaper", "Selling shares quickly", "Selling shares at a loss", "Selling small quantity of shares"], answer: "Selling shares you don't own to buy back cheaper" },
    { id: 50, category: "Stock Market Basics", difficulty: "Easy", question: "What is 'Face Value' of a share?", options: ["Original value stated in the certificate", "Current market price", "Future expected price", "The price at which IPO is issued"], answer: "Original value stated in the certificate" },

    // --- RBI & Monetary Policy ---
    { id: 51, category: "RBI & Monetary Policy", difficulty: "Easy", question: "When was RBI established?", options: ["1935", "1947", "1950", "1921"], answer: "1935" },
    { id: 52, category: "RBI & Monetary Policy", difficulty: "Medium", question: "Who is the current Governor of RBI? (As of 2024 context)", options: ["Shaktikanta Das", "Urjit Patel", "Raghuram Rajan", "Nirmala Sitharaman"], answer: "Shaktikanta Das" },
    { id: 53, category: "RBI & Monetary Policy", difficulty: "Hard", question: "What is 'Moral Suasion'?", options: ["A qualitative credit control method", "A quantitative method", "A type of tax", "A loan scheme"], answer: "A qualitative credit control method" },
    { id: 54, category: "RBI & Monetary Policy", difficulty: "Easy", question: "Which city is the headquarters of RBI?", options: ["Mumbai", "Delhi", "Kolkata", "Chennai"], answer: "Mumbai" },
    { id: 55, category: "RBI & Monetary Policy", difficulty: "Medium", question: "What is 'Cash Reserve Ratio (CRR)'?", options: ["Percentage of deposits banks must keep with RBI", "Percentage of cash kept in bank vault", "Percentage of gold reserves", "Interest rate on savings"], answer: "Percentage of deposits banks must keep with RBI" },
    { id: 56, category: "RBI & Monetary Policy", difficulty: "Hard", question: "What is the primary objective of Monetary Policy?", options: ["Price Stability & Growth", "Export Promotion", "Reducing Taxes", "Printing Currency"], answer: "Price Stability & Growth" },
    { id: 57, category: "RBI & Monetary Policy", difficulty: "Easy", question: "Who signs the ₹1 note in India?", options: ["Finance Secretary", "RBI Governor", "Finance Minister", "President of India"], answer: "Finance Secretary" },
    { id: 58, category: "RBI & Monetary Policy", difficulty: "Medium", question: "What is 'Open Market Operations (OMO)'?", options: ["Buying and selling of govt securities by RBI", "Opening new bank branches", "Selling shares in stock market", "Giving loans to public"], answer: "Buying and selling of govt securities by RBI" },
    { id: 59, category: "RBI & Monetary Policy", difficulty: "Hard", question: "What is 'Bank Rate'?", options: ["The rate at which RBI gives long-term loans to banks", "The rate at which banks give loans to public", "The rate of interest on FDs", "The rate of inflation"], answer: "The rate at which RBI gives long-term loans to banks" },
    { id: 60, category: "RBI & Monetary Policy", difficulty: "Easy", question: "How many deputy governors can RBI have?", options: ["4", "2", "3", "5"], answer: "4" },

    // --- Digital Banking ---
    { id: 61, category: "Digital Banking", difficulty: "Easy", question: "What is the full form of UPI?", options: ["Unified Payments Interface", "Universal Payment Index", "United Personal Identifier", "Unique Payment Interface"], answer: "Unified Payments Interface" },
    { id: 62, category: "Digital Banking", difficulty: "Medium", question: "Which organization developed UPI?", options: ["NPCI", "RBI", "SEBI", "NITI Aayog"], answer: "NPCI" },
    { id: 63, category: "Digital Banking", difficulty: "Hard", question: "What is 'Phishing'?", options: ["Fraudulent attempt to obtain sensitive info", "A type of digital loan", "A fast payment method", "A social media trend"], answer: "Fraudulent attempt to obtain sensitive info" },
    { id: 64, category: "Digital Banking", difficulty: "Easy", question: "What is 'Mobile Banking'?", options: ["Banking services via mobile phone", "Banking for mobile shop owners", "A bank on wheels", "Buying mobiles through bank"], answer: "Banking services via mobile phone" },
    { id: 65, category: "Digital Banking", difficulty: "Medium", question: "What is 'OTP'?", options: ["One Time Password", "Only To Person", "Open Trade Protocol", "On Time Payment"], answer: "One Time Password" },
    { id: 66, category: "Digital Banking", difficulty: "Hard", question: "What is 'Blockchain' in banking?", options: ["Distributed ledger technology", "A physical lock for vaults", "A chain of bank branches", "A type of loan security"], answer: "Distributed ledger technology" },
    { id: 67, category: "Digital Banking", difficulty: "Easy", question: "What is 'E-wallet'?", options: ["Digital version of a physical wallet", "An electronic lock", "A credit card chip", "A crypto currency"], answer: "Digital version of a physical wallet" },
    { id: 68, category: "Digital Banking", difficulty: "Medium", question: "What is 'NEFT'?", options: ["National Electronic Funds Transfer", "Net Equity Fund Trust", "Native Electronic Finance Tool", "National Energy Fund Transfer"], answer: "National Electronic Funds Transfer" },
    { id: 69, category: "Digital Banking", difficulty: "Hard", question: "What is 'CBDC'?", options: ["Central Bank Digital Currency", "Commercial Bank Digital Credit", "Cash Balance Digital Code", "Core Banking Digital Center"], answer: "Central Bank Digital Currency" },
    { id: 70, category: "Digital Banking", difficulty: "Easy", question: "What is the limit for contactless card payment without PIN in India? (Current standard)", options: ["₹5000", "₹2000", "₹10000", "₹1000"], answer: "₹5000" },

    // --- GST & Taxation ---
    { id: 71, category: "GST & Taxation", difficulty: "Easy", question: "What is the full form of GST?", options: ["Goods and Services Tax", "General Sales Tax", "Government Service Tax", "Global Standard Tax"], answer: "Goods and Services Tax" },
    { id: 72, category: "GST & Taxation", difficulty: "Medium", question: "When was GST implemented in India?", options: ["1st July 2017", "1st April 2017", "15th August 2016", "1st January 2018"], answer: "1st July 2017" },
    { id: 73, category: "GST & Taxation", difficulty: "Hard", question: "Which constitutional amendment introduced GST?", options: ["101st", "122nd", "42nd", "73rd"], answer: "101st" },
    { id: 74, category: "GST & Taxation", difficulty: "Easy", question: "What is 'Direct Tax'?", options: ["Tax paid directly by individual to govt", "Tax on goods and services", "GST", "Customs Duty"], answer: "Tax paid directly by individual to govt" },
    { id: 75, category: "GST & Taxation", difficulty: "Medium", question: "Income Tax is an example of?", options: ["Direct Tax", "Indirect Tax", "Value Added Tax", "Sales Tax"], answer: "Direct Tax" },
    { id: 76, category: "GST & Taxation", difficulty: "Hard", question: "What is 'Input Tax Credit (ITC)'?", options: ["Credit for tax paid on inputs", "A type of loan from bank", "Income tax refund", "A tax on exports"], answer: "Credit for tax paid on inputs" },
    { id: 77, category: "GST & Taxation", difficulty: "Easy", question: "Who is the chairman of the GST Council?", options: ["Union Finance Minister", "Prime Minister", "RBI Governor", "President"], answer: "Union Finance Minister" },
    { id: 78, category: "GST & Taxation", difficulty: "Medium", question: "How many digits are there in a GSTIN?", options: ["15", "10", "12", "16"], answer: "15" },
    { id: 79, category: "GST & Taxation", difficulty: "Hard", question: "What is 'IGST'?", options: ["Integrated GST", "Internal GST", "International GST", "Indian GST"], answer: "Integrated GST" },
    { id: 80, category: "GST & Taxation", difficulty: "Easy", question: "Which of these is NOT a GST slab?", options: ["15%", "5%", "12%", "28%"], answer: "15%" },

    // --- Insurance ---
    { id: 81, category: "Insurance", difficulty: "Easy", question: "What is 'Premium' in insurance?", options: ["Amount paid periodically for coverage", "The profit of company", "The claim amount", "The agent's commission"], answer: "Amount paid periodically for coverage" },
    { id: 82, category: "Insurance", difficulty: "Medium", question: "Who is the regulator of insurance in India?", options: ["IRDAI", "SEBI", "RBI", "NABARD"], answer: "IRDAI" },
    { id: 83, category: "Insurance", difficulty: "Hard", question: "What is 'Reinsurance'?", options: ["Insurance for insurance companies", "Insuring the same asset twice", "Cancelling insurance", "Life insurance only"], answer: "Insurance for insurance companies" },
    { id: 84, category: "Insurance", difficulty: "Easy", question: "LIC stands for?", options: ["Life Insurance Corporation", "Legal Insurance Center", "Loan Interest Company", "Life Investment Club"], answer: "Life Insurance Corporation" },
    { id: 85, category: "Insurance", difficulty: "Medium", question: "What is 'Term Insurance'?", options: ["Pure life cover for a specific period", "Investment + Insurance", "Health insurance", "Motor insurance"], answer: "Pure life cover for a specific period" },
    { id: 86, category: "Insurance", difficulty: "Hard", question: "The principle of 'Utmost Good Faith' is called?", options: ["Uberrimae Fidei", "Caveat Emptor", "Quid Pro Quo", "Status Quo"], answer: "Uberrimae Fidei" },
    { id: 87, category: "Insurance", difficulty: "Easy", question: "Which insurance is mandatory for vehicle owners in India?", options: ["Third Party Insurance", "Comprehensive Insurance", "Life Insurance", "Health Insurance"], answer: "Third Party Insurance" },
    { id: 88, category: "Insurance", difficulty: "Medium", question: "What is 'Annuity'?", options: ["Periodic payment for lifetime after retirement", "A one-time bonus", "A type of tax", "Insurance premium"], answer: "Periodic payment for lifetime after retirement" },
    { id: 89, category: "Insurance", difficulty: "Hard", question: "What is 'Actuary'?", options: ["Professional who calculates risks and premiums", "An insurance agent", "A bank manager", "A government officer"], answer: "Professional who calculates risks and premiums" },
    { id: 90, category: "Insurance", difficulty: "Easy", question: "What is 'Claim' in insurance?", options: ["Request to insurer for payment of loss", "Paying the premium", "Signing the policy", "Selling the policy"], answer: "Request to insurer for payment of loss" },

    // --- Management Principles ---
    { id: 91, category: "Management Principles", difficulty: "Easy", question: "Who is known as the Father of Scientific Management?", options: ["F.W. Taylor", "Henry Fayol", "Peter Drucker", "Max Weber"], answer: "F.W. Taylor" },
    { id: 92, category: "Management Principles", difficulty: "Medium", question: "How many principles of management were given by Henry Fayol?", options: ["14", "10", "12", "16"], answer: "14" },
    { id: 93, category: "Management Principles", difficulty: "Hard", question: "What is 'Unity of Command'?", options: ["Subordinate should receive orders from one boss only", "All employees should work together", "Manager should be strict", "Orders should be given in writing"], answer: "Subordinate should receive orders from one boss only" },
    { id: 94, category: "Management Principles", difficulty: "Easy", question: "What is 'Planning'?", options: ["Deciding in advance what to do", "Checking work", "Giving orders", "Hiring people"], answer: "Deciding in advance what to do" },
    { id: 95, category: "Management Principles", difficulty: "Medium", question: "What is 'SWOT Analysis'?", options: ["Strengths, Weaknesses, Opportunities, Threats", "Simple, Wide, Open, Trade", "Smart, Wise, Original, Team", "System, Work, Order, Task"], answer: "Strengths, Weaknesses, Opportunities, Threats" },
    { id: 96, category: "Management Principles", difficulty: "Hard", question: "What is 'Span of Management'?", options: ["Number of subordinates a manager can effectively supervise", "The time a manager spends in office", "The salary of a manager", "The area of the office"], answer: "Number of subordinates a manager can effectively supervise" },
    { id: 97, category: "Management Principles", difficulty: "Easy", question: "What is 'Staffing'?", options: ["Filling positions in organizational structure", "Buying stationery", "Cleaning the office", "Organizing a meeting"], answer: "Filling positions in organizational structure" },
    { id: 98, category: "Management Principles", difficulty: "Medium", question: "What is 'Delegation'?", options: ["Assigning work and authority to others", "Firing employees", "Promoting employees", "Reducing work"], answer: "Assigning work and authority to others" },
    { id: 99, category: "Management Principles", difficulty: "Hard", question: "Who proposed the 'Hierarchy of Needs' theory?", options: ["Abraham Maslow", "Douglas McGregor", "Herzberg", "Vroom"], answer: "Abraham Maslow" },
    { id: 100, category: "Management Principles", difficulty: "Easy", question: "What is 'Controlling'?", options: ["Monitoring performance and taking corrective action", "Restricting employees", "Setting high prices", "Closing the business"], answer: "Monitoring performance and taking corrective action" },

    // --- More Questions to ensure variety (100-200) ---
    { id: 101, category: "Banking Basics", difficulty: "Easy", question: "What is 'Bank Overdraft'?", options: ["Withdrawing more than the balance", "Paying more interest", "A type of fixed deposit", "A closed account"], answer: "Withdrawing more than the balance" },
    { id: 102, category: "Financial Accounting", difficulty: "Medium", question: "What is 'Depreciation'?", options: ["Reduction in value of fixed assets", "Increase in value", "Cash inflow", "Sales tax"], answer: "Reduction in value of fixed assets" },
    { id: 103, category: "Business Economics", difficulty: "Easy", question: "What is 'Inflation'?", options: ["General increase in prices", "Decrease in prices", "Stable prices", "Zero prices"], answer: "General increase in prices" },
    { id: 104, category: "Financial Management", difficulty: "Hard", question: "What is 'Capital Structure'?", options: ["Mix of debt and equity", "Building plan", "Management hierarchy", "Inventory level"], answer: "Mix of debt and equity" },
    { id: 105, category: "Stock Market Basics", difficulty: "Medium", question: "What is 'Market Capitalization'?", options: ["Total value of company's shares", "Total debt", "Total profit", "Total employees"], answer: "Total value of company's shares" },
    { id: 106, category: "RBI & Monetary Policy", difficulty: "Easy", question: "What is 'Reverse Repo Rate'?", options: ["Rate at which RBI borrows from banks", "Rate at which RBI lends to banks", "Rate of income tax", "Rate of GDP growth"], answer: "Rate at which RBI borrows from banks" },
    { id: 107, category: "Digital Banking", difficulty: "Easy", question: "What is 'Virtual Assistant' in banking?", options: ["AI chatbot for customer help", "A physical guard", "A branch manager", "A telephone operator"], answer: "AI chatbot for customer help" },
    { id: 108, category: "GST & Taxation", difficulty: "Medium", question: "What is 'SGST'?", options: ["State GST", "State Government Sales Tax", "Simple GST", "Super GST"], answer: "State GST" },
    { id: 109, category: "Insurance", difficulty: "Easy", question: "What is 'Nominee'?", options: ["Person who receives benefits after policyholder's death", "The insurance agent", "The bank manager", "The govt officer"], answer: "Person who receives benefits after policyholder's death" },
    { id: 110, category: "Management Principles", difficulty: "Medium", question: "What is 'MBO'?", options: ["Management by Objectives", "Management by Orders", "Money Banking Office", "Monthly Business Order"], answer: "Management by Objectives" }
];

// Shuffle helper for selection
function shuffleQuestions(array) {
  return [...array].sort(() => Math.random() - 0.5);
}

window.quizQuestions = questions;
